# Generated by Django 4.1.5 on 2023-07-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_open', models.IntegerField()),
                ('previous_close_price', models.IntegerField()),
                ('day_high', models.IntegerField()),
                ('day_low', models.IntegerField()),
                ('price', models.IntegerField()),
                ('last_trade_time', models.CharField(max_length=100)),
                ('_week_high', models.IntegerField()),
                ('_week_low', models.IntegerField()),
            ],
        ),
    ]
